[package]
name = "molecule"
version = "0.4.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "Rust bindings for molecule."
homepage = "https://github.com/nervosnetwork/molecule"
repository = "https://github.com/nervosnetwork/molecule"
keywords = ["serialization"]
categories = ["encoding", "data-structures"]
license = "MIT"

[features]
default = ["std"]
std = ["faster-hex"]

[dependencies]
bytes = { version = "~0.5", default-features = false }
failure = { version = "0.1", default-features = false, features = ["derive"] }
faster-hex = { version = "~0.4", optional = true }

[badges]
maintenance = { status = "experimental" }
